name: Check

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: |
          npm install
      - name: Tests and Coverage
        run: npm run test -- --coverage
      - name: Report to codecov
        if: ${{ matrix.node-version }} >= 14
        run: |
          ./node_modules/.bin/codecov
